apiVersion: v1
kind: Service
metadata:
  name: gatekeeper-extension-apiserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gatekeeper-extension-apiserver
  sessionAffinity: None
  type: ClusterIP