kind: ClusterRole
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - 'apiextensions.k8s.io'
    resources:
      - 'customresourcedefinitions'
    verbs:
      - '*'
  - apiGroups:
      - 'config.gatekeeper.sh'
      - 'constraints.gatekeeper.sh'
      - 'expansion.gatekeeper.sh'
      - 'externaldata.gatekeeper.sh'
      - 'mutations.gatekeeper.sh'
      - 'status.gatekeeper.sh'
      - 'templates.gatekeeper.sh'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - 'rbac.authorization.k8s.io'
    resources:
      - 'clusterroles'
      - 'clusterrolebindings'
    verbs:
      - 'create'
      - 'delete'
  - apiGroups:
      - ''
    resources:
      - 'namespaces'
    verbs:
      - 'patch'
      - 'update'
  - apiGroups:
      - 'rbac.authorization.k8s.io'
    resources:
      - 'clusterroles'
    verbs:
      - '*'
    resourceNames:
      - gatekeeper-manager-role
      - gatekeeper-admin-upgrade-crds
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - 'list'
  - apiGroups:
      - 'rbac.authorization.k8s.io'
    resources:
      - 'clusterrolebindings'
    verbs:
      - '*'
    resourceNames:
      - gatekeeper-manager-rolebinding
      - gatekeeper-admin-upgrade-crds
  - apiGroups:
      - 'policy'
    resources:
      - 'podsecuritypolicies'
    verbs:
      - '*'
    resourceNames:
      - gatekeeper-admin
  - apiGroups:
      - 'policy'
    resources:
      - 'podsecuritypolicies'
    verbs:
      - 'create'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - 'mutatingwebhookconfigurations'
    verbs:
      - '*'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - 'validatingwebhookconfigurations'
    verbs:
      - '*'
  - apiGroups:
      - 'extensions.kubesphere.io'
    resources:
      - '*'
    verbs:
      - '*'

---
kind: Role
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
