apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesphere:extension:gatekeeper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesphere:extension:gatekeeper
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}